version: '2'

services:
  postgres:
    restart: unless-stopped
    image: postgres:13.3-alpine
    env_file:
      - ../.env

  django:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "4000:4000"
    volumes:
      - ../:/app/
    depends_on:
      - postgres
    links:
      - "postgres:db"
    env_file:
      - ../.env
